apiVersion: v1
kind: Service
metadata:
  name: etcd-k8s
  namespace: kube-system
  labels:
    k8s-app: etcd
spec:
  clusterIP: None
  selector:
    component: etcd
  ports:
  - name: port
    port: 2379
    targetPort: 2379
    protocol: TCP
  type: ClusterIP    