apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: blackbox-exporter
    app.kubernetes.io/name: blackbox-exporter
  name: blackbox-exporter
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9115
    protocol: TCP
    targetPort: 9115
  selector:
    app.kubernetes.io/instance: blackbox-exporter
    app.kubernetes.io/name: blackbox-exporter
  type: ClusterIP