apiVersion: v1
data:
  blackbox.yaml: |
    modules:
      http_2xx:
        http:
          no_follow_redirects: false
          preferred_ip_protocol: ip4
          valid_http_versions:
          - HTTP/1.1
          - HTTP/2
        prober: http
        timeout: 5s
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: blackbox-exporter
    app.kubernetes.io/name: blackbox-exporter   
  name: blackbox-exporter-config
  namespace: monitoring