apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    alertmanager: main
  name: main
  namespace: monitoring
spec:
  image: ysicing/alertmanager:v0.20.0
  externalUrl: http://alertmanager.k7s.xyz
  retention: 240h
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: alertmanager-data-db
        resources:
          requests:
            storage: 10Gi  
  nodeSelector:
    kubernetes.io/os: linux
  replicas: 3
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager-main
  version: v0.20.0
