apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    alertmanager: main
  name: main
  namespace: monitoring
spec:
  image: registry.cn-beijing.aliyuncs.com/k7scn/alertmanager:v0.20.0
  externalUrl: http://alertmanager.k7s.local
  retention: 24h
  # storage:
  #   volumeClaimTemplate:
  #     spec:
  #       storageClassName: prometheus-data
  #       resources:
  #         requests:
  #           storage: 10Gi  
  nodeSelector:
    kubernetes.io/os: linux
  replicas: 3
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager-main
  version: v0.20.0
