# apiVersion: monitoring.coreos.com/v1
# kind: Prometheus
# metadata:
#   name: persisted
#   namespace: monitoring
# spec:
#   storage:
#     volumeClaimTemplate:
#       spec:
#         storageClassName: devk8s-bj
#         resources:
#           requests:
#             storage: 100Gi