apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: devk8s-bj
mountOptions:
- nolock,tcp,noresvport
- vers=3
parameters:
  server: <nasid>.cn-beijing.nas.aliyuncs.com:/k8s-prod-aliyun-beijing/monitordata
  volumeAs: subpath
provisioner: nasplugin.csi.alibabacloud.com
reclaimPolicy: Retain
volumeBindingMode: Immediate